<?xml version="1.0"?>
<robot name="ur3_pg70" xmlns:xacro="http://ros.org/wiki/xacro">

<xacro:include filename="$(find ur_description)/urdf/ur3_robot.urdf.xacro" />
<xacro:include filename="$(find schunk_pg70)/urdf/pg70.urdf.xacro" />

<!-- arm -->


<xacro:schunk_pg70 name="pg70" parent="tool0">
    <origin xyz="0 ${wrist_3_length/5} 0" rpy="0 0 0"/>
</xacro:schunk_pg70>

</robot>

